apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: volsync-restic-influxdb2
  namespace: influxdb
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/sjjphfngmqfdmjaaxq5n7zodu4"
