apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: kube-etcd
  namespace: monitoring
  labels:
    prometheus: kube-prometheus-stack-prometheus
    release: kube-prometheus-stack
spec:
  scheme: HTTP
  staticConfigs:
    - labels:
        endpoint: http-metrics
        job: kube-etcd
        namespace: kube-system
        service: kube-prometheus-stack-kube-etcd
      targets:
        - 10.0.40.11:2381
        - 10.0.40.12:2381
        - 10.0.40.13:2381
