apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: alertmanager-discord-webhooks
  namespace: monitoring
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/4ulkrswzhjkyfajnki3j3ba3by"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: grafana-admin-user
  namespace: monitoring
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/tpesk4qre5xwtrtrlaavxnwlka"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: grafana-oidc-client-secret
  namespace: monitoring
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/ii2ofjuq4j4ao2hreopxrsthuu"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: grafana-postgres-barman-s3
  namespace: monitoring
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/tqsjyf5bofbtsoxrzicwjf2idi"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: volsync-restic-prometheus-db
  namespace: monitoring
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/hawwb3zu7r3k65apqfrrlacsdq"
