apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: alertmanager-discord-webhooks
  namespace: monitoring
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/4ulkrswzhjkyfajnki3j3ba3by"
