nameOverride: "kube-prometheus-stack"

crds:
  enabled: true

grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin-user
    userKey: admin-user
    passwordKey: admin-password
  ingress:
    enabled: true
    ingressClassName: cloudflare-tunnel
    hosts:
      - grafana.akatuki-host.com
    path: /
    pathType: Prefix

prometheus:
  enabled: true
  prometheusSpec:
    retention: 10d

alertmanager:
  enabled: true
  alertmanagerSpec:
    secrets:
      - alertmanager-discord-webhooks
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by:
        - alertname
        - namespace
        - severity
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: discord-warning
      routes:
        - matchers:
            - severity="critical"
          receiver: discord-critical
          group_wait: 10s
          repeat_interval: 30m
        - matchers:
            - severity="warning"
          receiver: discord-warning
          group_wait: 30s
          repeat_interval: 2h
        - matchers:
            - severity="info"
          receiver: discord-info
          group_wait: 2m
          repeat_interval: 12h
    inhibit_rules:
      - source_matchers:
          - severity="critical"
        target_matchers:
          - severity="warning"
        equal:
          - alertname
          - namespace
    receivers:
      - name: discord-critical
        webhook_configs:
          - url_file: /etc/alertmanager/secrets/alertmanager-discord-webhooks/discord_webhook_critical
            send_resolved: true
      - name: discord-warning
        webhook_configs:
          - url_file: /etc/alertmanager/secrets/alertmanager-discord-webhooks/discord_webhook_warning
            send_resolved: true
      - name: discord-info
        webhook_configs:
          - url_file: /etc/alertmanager/secrets/alertmanager-discord-webhooks/discord_webhook_info
            send_resolved: true
