apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: rook-ceph-mon-endpoints
  namespace: rook-ceph
data:
  data: "a=192.168.8.101:3300,b=192.168.8.102:3300"
  maxMonId: "1"
  mapping: "{}"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: rook-ceph-mon
  namespace: rook-ceph
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/6dreqlxgw3fsj5ktcow7cz75e4"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: rook-ceph-operator-creds
  namespace: rook-ceph
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/krbr7kr2qm5zdvue7vq5a2st4e"
---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: rook-ceph-external
  namespace: rook-ceph
spec:
  external:
    enable: true
  crashCollector:
    disable: true
  dataDirHostPath: /var/lib/rook
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.3
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: external-rgw
  namespace: rook-ceph
spec:
  gateway:
    port: 7480
    externalRgwEndpoints:
      - ip: 192.168.8.102
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: rook-ceph-external-rgw
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: external-rgw
  objectStoreNamespace: rook-ceph
