apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: bgp-pool
  namespace: metallb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/component: bgp-pool
spec:
  addresses:
    - 10.127.0.1-10.127.0.254
  # autoAssign: false にすると、ServiceのannotationでPool名を指定した場合のみ割り当て
  # true にすると type: LoadBalancer のServiceに自動割り当て
  autoAssign: true
