apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
resources:
  - audit/disallow-privileged.yaml
  - audit/disallow-host-namespaces.yaml
  - audit/disallow-latest-tag.yaml
  - audit/require-requests-limits.yaml
  - audit/require-run-as-non-root.yaml
  - audit/require-drop-capabilities.yaml
  - audit/restrict-automount-serviceaccount-token.yaml
