apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  sourceRepos:
    - https://github.com/AkatukiSora/k8s-deploys.git
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: argoproj.io
      kind: AppProject
  namespaceResourceWhitelist:
    - group: argoproj.io
      kind: Application
    - group: ""
      kind: ConfigMap
