apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: authentik-blueprints-oidc
  namespace: authentik
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/ehzbo7qccalsziygrdz7fzomge"
