apiVersion: v1
kind: Namespace
metadata:
  name: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
---
apiVersion: v1
kind: Namespace
metadata:
  name: immich-postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: volsync-restic-immich-library
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/3r3heyslbmvpjx6ntjbptr7iby"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-rbd
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: immich-library-restore
  namespace: immich
spec:
  trigger:
    manual: restore-latest
  restic:
    destinationPVC: immich-library
    repository: volsync-restic-immich-library
    copyMethod: Direct
---
apiVersion: v1
kind: Namespace
metadata:
  name: vikunja
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: volsync-restic-vikunja-data
  namespace: vikunja
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/uiuputhszcnsyt4cpvuano2mae"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-data
  namespace: vikunja
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-rbd
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: vikunja-data-restore
  namespace: vikunja
spec:
  trigger:
    manual: restore-latest
  restic:
    destinationPVC: vikunja-data
    repository: volsync-restic-vikunja-data
    copyMethod: Direct
---
apiVersion: v1
kind: Namespace
metadata:
  name: influxdb
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: volsync-restic-influxdb2
  namespace: influxdb
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/sjjphfngmqfdmjaaxq5n7zodu4"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-db-influxdb2
  namespace: influxdb
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ceph-rbd
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: influxdb2-data-restore
  namespace: influxdb
spec:
  trigger:
    manual: restore-latest
  restic:
    destinationPVC: influx-db-influxdb2
    repository: volsync-restic-influxdb2
    copyMethod: Direct
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: volsync-restic-prometheus-db
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/hawwb3zu7r3k65apqfrrlacsdq"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ceph-rbd
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: prometheus-db-restore
  namespace: monitoring
spec:
  trigger:
    manual: restore-latest
  restic:
    destinationPVC: prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0
    repository: volsync-restic-prometheus-db
    copyMethod: Direct
