apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: csi-cephfs-secret
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/civwq6wfcmjjmj5r6aaqeqgjom"
  