apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
  namespace: authentik
  annotations:
    alpha.cnpg.io/failoverQuorum: "true"
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  postgresql:
    synchronous:
      method: any
      number: 1
      dataDurability: required
  bootstrap:
    recovery:
      source: backup
  storage:
    size: 20Gi
    storageClass: ceph-rbd
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: authentik-postgres-barman-store
  externalClusters:
    - name: backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: authentik-postgres-barman-store
          serverName: authentik-postgres
  monitoring:
    enablePodMonitor: true
