apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: authentik-postgres-barman-s3
  namespace: authentik
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/pjfpol66v3bfvlklhtezb7mxlm"
