apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: volsync-restic-canary
  namespace: volsync-canary
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/n4w44omqhyoiqtpv3ha6xwfcme"
