apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: volsync-canary-data
  namespace: volsync-canary
spec:
  sourcePVC: volsync-canary-data
  trigger:
    schedule: "0 */6 * * *"
  restic:
    repository: volsync-restic-canary
    copyMethod: Snapshot
    storageClassName: ceph-rbd
    volumeSnapshotClassName: csi-rbdplugin-snapclass
    cacheCapacity: 1Gi
    cacheStorageClassName: ceph-rbd
    pruneIntervalDays: 7
    retain:
      hourly: 2
      daily: 2
      weekly: 1
      monthly: 1
