apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync-canary-restore
  namespace: volsync-canary
spec:
  trigger:
    manual: restore-once
  restic:
    repository: volsync-restic-canary
    destinationPVC: volsync-canary-restore
    copyMethod: Direct
    cacheCapacity: 1Gi
    cacheStorageClassName: ceph-rbd
