postgresql:
  enabled: false

authentik:
  existingSecret:
    secretName: authentik-secret
  error_reporting:
    enabled: false

global:
  env:
    - name: AUTHENTIK_POSTGRESQL__HOST
      value: authentik-postgres-rw.authentik
    - name: AUTHENTIK_POSTGRESQL__PORT
      value: "5432"
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__USER
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-app
          key: username
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-app
          key: password
  envFrom:
    - secretRef:
        name: authentik-smtp
    - secretRef:
        name: authentik-blueprints-oidc

blueprints:
  configMaps:
    - authentik-blueprints

server:
  replicas: 2
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: server
              app.kubernetes.io/instance: authentik
              app.kubernetes.io/name: authentik
          topologyKey: kubernetes.io/hostname
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  securityContext:
    runAsNonRoot: true
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  ingress:
    enabled: true
    ingressClassName: cloudflare-tunnel
    annotations:
      kubernetes.io/ingress.class: cloudflare-tunnel
    hosts:
      - auth.akatuki-host.com

worker:
  replicas: 2
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: worker
              app.kubernetes.io/instance: authentik
              app.kubernetes.io/name: authentik
          topologyKey: kubernetes.io/hostname
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  securityContext:
    runAsNonRoot: true
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
