apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: vikunja-secret
  namespace: vikunja
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/5zjd5bm2js7ds64iiris5axerm"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: vikunja-oidc-client-secret
  namespace: vikunja
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/kbve2a7stpyex2uzigeptndc4i"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: vikunja-postgres-barman-s3
  namespace: vikunja
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/imgm7q7sc7juqvhcjghzezumhu"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: volsync-restic-vikunja-data
  namespace: vikunja
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/uiuputhszcnsyt4cpvuano2mae"
