apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: csi-rbd-secret
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/7no5skpgjkjt6sbwdgmjuyt7oq"
  