apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgres
  namespace: nextcloud
  annotations:
    alpha.cnpg.io/failoverQuorum: "true"
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  postgresql:
    synchronous:
      method: any
      number: 1
      dataDurability: required
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
  storage:
    size: 10Gi
    storageClass: ceph-rbd
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: nextcloud-postgres-barman-store
  monitoring:
    enablePodMonitor: true
