apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nextcloud-postgres-barman-daily
  namespace: nextcloud
spec:
  schedule: "0 30 1 * * *"
  suspend: false
  backupOwnerReference: self
  cluster:
    name: nextcloud-postgres
  method: plugin
  target: prefer-standby
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
