apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  destination:
    namespace: nextcloud
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://nextcloud.github.io/helm/
      targetRevision: 6.6.8
      chart: nextcloud
      helm:
        valueFiles:
          - $repo/values.yaml
    - repoURL: https://github.com/AkatukiSora/k8s-deploys.git
      targetRevision: master
      path: apps/nextcloud
      ref: repo
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
