redis:
  enabled: true
internalDatabase:
  enabled: false
mariadb:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  host: nextcloud-postgres-rw
  database: nextcloud
  existingSecret:
    enabled: true
    secretName: nextcloud-postgres-app
    usernameKey: username
    passwordKey: password
persistence:
  storageClass: ceph-cephfs
  enabled: true
  accessMode: ReadWriteMany
  size: 100Gi
cronjob:
  enabled: true
hpa:
  enabled: false
ingress:
  enabled: true
  className: cloudflare-tunnel
  annotations:
    kubernetes.io/ingress.class: cloudflare-tunnel
nextcloud:
  host: "nextcloud.akatuki-host.com"
  existingSecret:
    enabled: true
    secretName: nextcloud-admin
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password
  trustedDomains:
    - "nextcloud.akatuki-host.com"
  extraEnv:
    - name: NEXTCLOUD_OIDC_CLIENT_ID
      value: "nextcloud"
    - name: NEXTCLOUD_OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: nextcloud-oidc-client-secret
          key: client-secret
    - name: NEXTCLOUD_OIDC_DISCOVERY_URL
      value: "https://auth.akatuki-host.com/application/o/nextcloud/.well-known/openid-configuration"
  extraInitContainers:
    - name: wait-for-postgres
      image: ghcr.io/cloudnative-pg/postgresql:18.0-system-trixie
      command:
        - sh
        - -ec
        - |
          until pg_isready -h nextcloud-postgres-rw -p 5432 -d nextcloud -U nextcloud; do
            sleep 2
          done
  configs:
    trusted_proxy.config.php: |
      <?php
      $CONFIG = array (
        'trusted_domains' => [
          'nextcloud.akatuki-host.com',
        ],
        'trusted_proxies'   => [
          '10.244.0.0/16',
        ],
        'forwarded_for_headers' => ['HTTP_X_FORWARDED_FOR'],
        'overwriteprotocol' => 'https',
        'overwrite.cli.url' => 'https://nextcloud.akatuki-host.com/',
      );
    oidc.config.php: |
      <?php
      $CONFIG = array (
        'user_oidc' => array (
          'login_label' => 'Sign in with Authentik',
          'auto_provision' => true,
          'soft_auto_provision' => true,
          'disable_account_creation' => false,
          'single_logout' => true,
          'send_userinfo_claims' => false,
          'use_pkce' => true,
        ),
      );
