apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: security-trivy-rules
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: security.trivy
      rules:
        - alert: TrivyOperatorDown
          expr: sum(up{namespace="trivy-system",pod=~"trivy-operator.*"}) < 1
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Trivy Operator is down
            runbook_url: https://aquasecurity.github.io/trivy-operator/
        - alert: TrivyCriticalVulnerabilitiesDetected
          expr: sum(trivy_image_vulnerabilities{severity="Critical"}) > 0
          for: 30m
          labels:
            severity: warning
          annotations:
            summary: Critical vulnerabilities detected by Trivy
            runbook_url: https://aquasecurity.github.io/trivy-operator/
        - alert: TrivyExposedSecretsDetected
          expr: sum(trivy_resource_exposedsecrets{severity="CRITICAL"}) > 0
          for: 30m
          labels:
            severity: warning
          annotations:
            summary: Exposed secrets detected by Trivy
            runbook_url: https://aquasecurity.github.io/trivy-operator/
