apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vikunja-postgres
  namespace: vikunja
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: vikunja
      owner: vikunja
      secret:
        name: vikunja-postgres-app
  superuserSecret:
    name: vikunja-postgres-superuser
  storage:
    size: 10Gi
    storageClass: ceph-rbd
  monitoring:
    enablePodMonitor: true
