apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: vikunja-postgres-superuser
  namespace: vikunja
spec:
  itemPath: "vaults/<vault-id>/items/<item-id>"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: vikunja-postgres-app
  namespace: vikunja
spec:
  itemPath: "vaults/<vault-id>/items/<item-id>"
