apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password
spec:
  destination:
    namespace: 1password
    server: https://kubernetes.default.svc
  sources: 
    - path: ''
      repoURL: https://1password.github.io/connect-helm-charts/
      targetRevision: 1.17.0
      chart: connect
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
