apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: 1password
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 1password
    server: https://kubernetes.default.svc
  sources: 
    - path: ''
      repoURL: https://1password.github.io/connect-helm-charts/
      targetRevision: 2.4.1
      helm:
        valueFiles:
          - $repo/apps/1password/values.yaml

      chart: connect
    - repoURL: https://github.com/AkatukiSora/k8s-deploys
      targetRevision: master
      ref: repo
      path: apps/1password
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/tracking-id: "1password:/Namespace:1password/1password"
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
