apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-rollouts
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-rollouts
      targetRevision: 2.38.0
      helm:
        valuesObject:
          dashboard:
            enabled: true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      managedFieldsManagers:
        - kube-apiserver
        - argocd-controller
  syncPolicy:
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/tracking-id: "argo-rollouts:/Namespace:argo-rollouts/argo-rollouts"
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
