apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caddy-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: caddy-test
  project: default
  source:
    path: apps/caddy
    repoURL: https://github.com/AkatukiSora/k8s-deploys.git
    targetRevision: master
  syncPolicy:
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/tracking-id: "caddy-test:/Namespace:caddy-test/caddy-test"
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
