apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capsule
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    namespace: capsule-system
    server: https://kubernetes.default.svc
  project: platform
  sources:
    - repoURL: https://projectcapsule.github.io/charts
      chart: capsule
      targetRevision: 0.13.9
      helm:
        valueFiles:
          - $repo/apps/capsule/values.yaml
    - repoURL: https://github.com/AkatukiSora/k8s-deploys.git
      targetRevision: master
      ref: repo
      path: apps/capsule
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
