apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/cert-manager
    repoURL: https://github.com/AkatukiSora/k8s-deploys.git
    targetRevision: master
  syncPolicy:
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/tracking-id: "cert-manager:/Namespace:cert-manager/cert-manager"
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
