apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-operator
  namespace: argocd
spec:
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/cloudnative-pg/charts.git
      path: charts/cloudnative-pg
      targetRevision: cloudnative-pg-v0.26.1
      helm:
        releaseName: cloudnative-pg
        valueFiles:
          - $values/apps/cloudnative-pg-operator/values.yaml
    - repoURL: https://github.com/AkatukiSora/k8s-deploys.git
      targetRevision: master
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
