apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  destination:
    namespace: coder
    server: https://kubernetes.default.svc
  project: soras-tenant
  sources:
    - repoURL: https://helm.coder.com/v2
      chart: coder
      targetRevision: 2.34.3
      helm:
        releaseName: coder
        valueFiles:
          - $repo/apps/coder/values.yaml
    - repoURL: https://github.com/AkatukiSora/k8s-deploys.git
      targetRevision: master
      ref: repo
      path: apps/coder
      directory:
        exclude: values.yaml
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      name: coder-postgres
      namespace: coder
      jsonPointers:
        - /spec
        - /metadata/annotations
        - /metadata/labels
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
