apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cryptpad
  namespace: argocd
spec:
  destination:
    namespace: cryptpad
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/cryptpad
    repoURL: https://github.com/AkatukiSora/k8s-deploys.git
    targetRevision: master
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: cryptpad
      namespace: cryptpad
      jsonPointers:
        - /spec/template/metadata/annotations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
