apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  source:
    path: 'apps/grafana-tools/grafana'
    repoURL: https://github.com/AkatukiSora/k8s-deploys.git
    targetRevision: 'master'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
    - CreateNamespace=true