apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  destination:
    namespace: immich
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/immich-app/immich-charts.git
      path: charts/immich
      targetRevision: immich-0.11.1
      helm:
        releaseName: immich
        valueFiles:
          - $values/apps/immich/values.yaml
    - repoURL: https://github.com/AkatukiSora/k8s-deploys.git
      targetRevision: master
      ref: values
    - repoURL: https://github.com/AkatukiSora/k8s-deploys.git
      path: apps/immich/manifests
      targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
