apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mender-mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/AkatukiSora/k8s-deploys.git
    targetRevision: master
    path: apps/mender/mongodb
  destination:
    server: https://kubernetes.default.svc
    namespace: mender
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
