apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metal-lb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: metallb
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://metallb.github.io/metallb
      targetRevision: 0.16.1
      chart: metallb
      helm:
        valueFiles:
          - $repo/apps/metallb/values.yaml
    - repoURL: https://github.com/AkatukiSora/k8s-deploys.git
      targetRevision: master
      ref: repo
      path: apps/metallb/bgp

  project: default
  syncPolicy:
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/tracking-id: "metal-lb:/Namespace:metallb/metallb"
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
