apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: metrics-server
    server: https://kubernetes.default.svc
  project: platform
  sources:
    - repoURL: https://github.com/AkatukiSora/k8s-deploys.git
      targetRevision: master
      ref: repo
      path: apps/metrics-server
      directory:
        exclude: '{values.yaml,**/values.yaml,**/*values*.yaml}'
    - repoURL: https://kubernetes-sigs.github.io/metrics-server/
      chart: metrics-server
      targetRevision: 3.13.1
      helm:
        valueFiles:
          - $repo/apps/metrics-server/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
