apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
spec:
  destination:
    namespace: nfs-provisioner
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    chart: nfs-subdir-external-provisioner
    helm:
      values: |-
        nfs:
          path: "/export/k8s"
          server: "10.1.0.6"
        storageClass:
          defaultClass: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
