apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pjserver-sys
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: pjserver-sys
  project: default
  source:
    path: kubernetes
    repoURL: https://github.com/AkatukiSora/pjserver-sys.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
