apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pjserver-sys
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: pjserver-sys
  project: default
  source:
    path: kubernetes
    repoURL: https://github.com/AkatukiSora/pjserver-sys.git
    targetRevision: master
  syncPolicy:
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/tracking-id: "pjserver-sys:/Namespace:pjserver-sys/pjserver-sys"
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
