apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plugin-barman-cloud
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: apps/plugin-barman-cloud
    repoURL: https://github.com/AkatukiSora/k8s-deploys.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
