apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restore-data
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: platform
  source:
    path: apps/restore
    repoURL: https://github.com/AkatukiSora/k8s-deploys.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
