apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-prometheus-rules
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: default
  source:
    repoURL: https://github.com/AkatukiSora/k8s-deploys.git
    targetRevision: master
    path: apps/security/prometheus-rules
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
