apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: grafana
  name: grafana-config
data:
  grafana.ini: |
    [server]
    protocol = http
    http_port = 3000
    root_url = https://grafana.akatuki-host.com/
    serve_from_sub_path = false
    enable_gzip = true
    # 追加設定
    use_x_forwarded_proto = true
