apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    operator.1password.io/auto-restart: "true"
  name: hermes-github-app
  namespace: hermes
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/hermes-github-app"
