apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-google-secretary-data
  namespace: hermes
  labels:
    app.kubernetes.io/instance: hermes
    app.kubernetes.io/name: hermes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-rbd
