# 1password-credentials.jsonをbase64エンコードしたものと
# JWTトークンをbase64エンコードしたものを別途デプロイしてください。
# なお1password-credentials.jsonはbase64エンコードされた状態でconnect serverに渡る必要があります
# 二重にエンコードしたものをdataにセットするようにしてください

apiVersion: v1
kind: Secret
metadata:
  name: "op-credentials"
type: Opaque
data:
  1password-credentials.json: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: "onepassword-token"
type: Opaque
data:
  token: ""