apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: nextcloud-admin
  namespace: nextcloud
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/zmp343pm5gdi2th53wcf622lbe"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: nextcloud-oidc-client-secret
  namespace: nextcloud
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/uxz5f7je4meq74va4g4h6rog5y"
