apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: immich-postgres
spec:
  instances: 1
  postgresUID: 999
  postgresGID: 999
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: immich-postgres
    major: 17
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  bootstrap:
    recovery:
      source: backup
  superuserSecret:
    name: immich-postgres-superuser
  storage:
    size: 30Gi
    storageClass: ceph-rbd
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi
  postgresql:
    shared_preload_libraries:
      - vchord.so
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: immich-postgres-barman-store
  monitoring:
    enablePodMonitor: true
  backup:
    volumeSnapshot:
      className: csi-rbdplugin-snapclass
  externalClusters:
    - name: backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: immich-postgres-barman-store
          serverName: immich-postgres
