apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: immich-postgres-superuser
  namespace: immich-postgres
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/lqueunpinyfcriz3e4hkixke2u"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: immich-postgres-app
  namespace: immich-postgres
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/jo4m525ctw5v2te24in7uy6sz4"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: immich-postgres-barman-s3
  namespace: immich-postgres
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/mr2u4u53ppp63cxjvhcgmwctja"
