apiVersion: v1
kind: Namespace
metadata:
  name: caddy-test
  labels:
    capsule.clastix.io/tenant: soras-tenant
---
apiVersion: v1
kind: Namespace
metadata:
  name: coder
  labels:
    capsule.clastix.io/tenant: soras-tenant
---
apiVersion: v1
kind: Namespace
metadata:
  name: immich
  labels:
    capsule.clastix.io/tenant: soras-tenant
---
apiVersion: v1
kind: Namespace
metadata:
  name: immich-postgres
  labels:
    capsule.clastix.io/tenant: soras-tenant
---
apiVersion: v1
kind: Namespace
metadata:
  name: influxdb
  labels:
    capsule.clastix.io/tenant: soras-tenant
---
apiVersion: v1
kind: Namespace
metadata:
  name: pjserver-sys
  labels:
    capsule.clastix.io/tenant: soras-tenant
---
apiVersion: v1
kind: Namespace
metadata:
  name: vikunja
  labels:
    capsule.clastix.io/tenant: soras-tenant
