apiVersion: v1
kind: Config
clusters:
  - name: k8s-soralab
    cluster:
      server: https://c1.k8s.internal:6443
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpVENDQVMrZ0F3SUJBZ0lRS1NXM2RQMkFENE5iVnI0eTFZYldPakFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTJNRFl5TmpFME16WXpNRm9YRFRNMk1EWXlNekUwTXpZegpNRm93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCQUxFZDVSbElJNCtranYxcWtVczlxZVdoWHRNTlNQWDdoRUdvdTRVZ3VxdGRXWFJ1YjNTQkVWNnFTaW4KRWkyb3cwemdyajZ5TlByUHQ2VTZaUDJIYWlHallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVUrYTFPakpYMHF3YlJZU2h5VVVLeWxueTNHejB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnSHUrZVVuMksKL050N2dJQ3FQcll1dUJhcXdXS0l4Y0pMUFgvU3RSSUR2c01DSVFENk9nYWoxQmJOMjdRUmZGb0dhTDBZUk5xQwplSUNnWVJNRjdPTVRPaWZucmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
users:
  - name: oidc
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1
        args:
        - oidc-login
        - get-token
        - --oidc-issuer-url=https://auth.akatuki-host.com/application/o/kubernetes/
        - --oidc-client-id=kubernetes-cluster
        - --oidc-extra-scope=profile
        command: kubectl
        env: null
        interactiveMode: Never
        provideClusterInfo: false

contexts:
  - name: oidc@k8s-soralab
    context:
      cluster: k8s-soralab
      user: oidc
      namespace: default
current-context: oidc@k8s-soralab
