apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: authentik-secret
  namespace: authentik
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/4cyvt4q4fybgcxi3k4mph2aauy"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: authentik-smtp
  namespace: authentik
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/3yajkjcib6tlxo3k2j2fbdhwga"
