apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    operator.1password.io/auto-restart: "true"
  name: mediamtx-rtmp-auth
  namespace: mediamtx
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/5iviw7o42o7zmaltzoga3jklw4"
