apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: mediamtx
  name: mediamtx
  namespace: mediamtx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mediamtx
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
