apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: immich-allow-ingress
  namespace: immich
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/instance
        operator: Exists
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cloudflare-tunnel-ingress-controller
      ports:
        - protocol: TCP
          port: 2283
