apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: immich-postgres-app
  namespace: immich
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/jo4m525ctw5v2te24in7uy6sz4"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: immich-oidc-client-secret
  namespace: immich
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/2ajavpo76qvxvgemoqpdr4sd34"
