apiVersion: v1
kind: ConfigMap
metadata:
  name: cryptpad-config
  namespace: cryptpad
data:
  config.js: |
    module.exports = {
      httpAddress: '0.0.0.0',
      httpPort: 3000,
      maxUploadSize: 100 * 1024 * 1024,
      httpUnsafeOrigin: 'https://pad.akatuki-host.com',
      httpSafeOrigin: 'https://pad-sandbox.akatuki-host.com',
      websocketPort: 3003,
    };
  application_config.template.js: |
    window.AppConfig = window.AppConfig || {};
    var AppConfig = window.AppConfig;
    define(['/common/application_config_internal.js'], function (InternalAppConfig) {
      Object.assign(AppConfig, InternalAppConfig);
      return AppConfig;
    });
