apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptpad-pvc
  namespace: cryptpad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: ceph-rbd
