apiVersion: v1
kind: Service
metadata:
  name: cryptpad
  namespace: cryptpad
  labels:
    app.kubernetes.io/name: cryptpad
spec:
  selector:
    app.kubernetes.io/name: cryptpad
  ports:
    - name: main
      port: 3000
      targetPort: main
    - name: sandbox
      port: 3001
      targetPort: 3000
  type: ClusterIP
