apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: cloudflare-external-secret
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/ifqdofmralbq3zuxdkpb4qzkf4"