admissionController:
  replicas: 2
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack

backgroundController:
  replicas: 1
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack

cleanupController:
  enabled: false

reportsController:
  replicas: 1
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack

grafana:
  enabled: false

features:
  policyReports:
    enabled: true

webhooksCleanup:
  image:
    registry: registry.k8s.io
    repository: kubectl
    tag: v1.30.2

policyReportsCleanup:
  image:
    registry: registry.k8s.io
    repository: kubectl
    tag: v1.30.2
