---
admissionController:
  replicas: 2
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack

backgroundController:
  enabled: false
  replicas: 1
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack

cleanupController:
  enabled: false

reportsController:
  enabled: false
  replicas: 1
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack

grafana:
  enabled: false

features:
  admissionReports:
    enabled: false
  aggregateReports:
    enabled: false
  policyReports:
    enabled: false
  validatingAdmissionPolicyReports:
    enabled: false
  backgroundScan:
    enabled: false
