apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: coder-oidc-client-secret
  namespace: coder
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/3helb26yroqdhnjcpcomt322sa"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  name: coder-postgres-barman-s3
  namespace: coder
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/uyxsedvevhhdhu4u2k7iwq5ph4"
