apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-postgres
  namespace: coder
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: coder
      owner: coder
  storage:
    size: 10Gi
    storageClass: ceph-rbd
  monitoring:
    enablePodMonitor: true
