apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-postgres
  namespace: coder
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  bootstrap:
    recovery:
      source: backup
  storage:
    size: 10Gi
    storageClass: ceph-rbd
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: coder-postgres-barman-store
  externalClusters:
    - name: backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: coder-postgres-barman-store
          serverName: coder-postgres
  monitoring:
    enablePodMonitor: true
