apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-ngx-ingress
  namespace: paperless-ngx
spec:
  ingressClassName: cloudflare-tunnel
  rules:
  - host: docmgr.akatuki-host.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webserver
            port:
              name: "http"
