apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
      -d --volumes persistentVolumeClaim --controller deployments
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: webserver
  name: webserver
  namespace: paperless-ngx
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: webserver
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tika
  namespace: paperless-ngx
spec:
  selector:
    io.kompose.service: tika
  ports:
  - name: tika
    protocol: TCP
    port: 9998
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: paperless-ngx
spec:
  selector:
    io.kompose.service: db
  ports:
  - name: postgresql
    protocol: TCP
    port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: paperless-ngx
spec:
  selector:
    io.kompose.service: broker
  ports:
  - protocol: TCP
    port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: gotenberg
  namespace: paperless-ngx
spec:
  selector:
    io.kompose.service: gotenberg
  ports:
  - protocol: TCP
    port: 3000