name: Cloudflare Terraform validation

on:
  pull_request:
    paths:
      - terraform/cloudflare/**
      - .github/workflows/cloudflare-terraform.yml
      - .github/workflows/cloudflare-terraform-operation.yml
      - .github/workflows/cloudflare-terraform-pr-plan.yml
  push:
    branches:
      - master
    paths:
      - terraform/cloudflare/**
      - .github/workflows/cloudflare-terraform.yml
      - .github/workflows/cloudflare-terraform-operation.yml
      - .github/workflows/cloudflare-terraform-pr-plan.yml

permissions:
  contents: read

jobs:
  cloudflare-terraform-validate:
    name: cloudflare-terraform-validate
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform/cloudflare
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: 1.16.5
          terraform_wrapper: false

      - name: Check formatting
        run: terraform fmt -check -recursive

      - name: Initialize providers without backend
        run: terraform init -backend=false -input=false

      - name: Validate configuration
        run: terraform validate -no-color
