apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  server.insecure: "true"
  server.enable.proxy.extension: "true"
  resource.customizations.health.postgresql.cnpg.io_Cluster: |
    hs = {}
    if obj.status == nil then
      hs.status = "Progressing"
      hs.message = "Waiting for Cluster status"
      return hs
    end

    if obj.status.phase ~= nil then
      if obj.status.phase == "Cluster in healthy state" then
        hs.status = "Healthy"
      else
        hs.status = "Progressing"
      end

      if obj.status.phaseReason ~= nil then
        hs.message = obj.status.phaseReason
      else
        hs.message = obj.status.phase
      end
      return hs
    end

    hs.status = "Progressing"
    hs.message = "Waiting for Cluster phase"
    return hs
