apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.akatuki-host.com
  oidc.config: |
    name: Authentik
    issuer: https://auth.akatuki-host.com/application/o/argocd/
    clientID: argocd
    clientSecret: $argocd-oidc-client-secret:client-secret
    requestedScopes: ["openid", "profile", "email"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
  extension.config: |
    extensions:
      - name: argo-rollouts
        backend:
          services:
            - url: http://argo-rollouts-dashboard.argo-rollouts.svc.cluster.local:3100
  resource.customizations.health.postgresql.cnpg.io_Cluster: |
    hs = {}
    if obj.status == nil then
      hs.status = "Progressing"
      hs.message = "Waiting for Cluster status"
      return hs
    end

    if obj.status.phase ~= nil then
      if obj.status.phase == "Cluster in healthy state" then
        hs.status = "Healthy"
      else
        hs.status = "Progressing"
      end

      if obj.status.phaseReason ~= nil then
        hs.message = obj.status.phaseReason
      else
        hs.message = obj.status.phase
      end
      return hs
    end

    hs.status = "Progressing"
    hs.message = "Waiting for Cluster phase"
    return hs
