apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  annotations:
    operator.1password.io/auto-restart: "true"
  labels:
    app.kubernetes.io/part-of: argocd
  name: argocd-oidc-client-secret
  namespace: argocd
spec:
  itemPath: "vaults/ehfcjhym4ifnf5qu634gng55mi/items/3herf5e5jclrj6bxtu7vitzxvm"
